# Generated by Django 2.1.4 on 2018-12-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpletire', '0002_reading_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='price',
            new_name='price_pennies',
        ),
    ]
