# Generated by Django 2.1.7 on 2019-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpletire', '0004_auto_20190129_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
