# Generated by Django 2.1.7 on 2019-02-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpletire', '0005_auto_20190223_1424'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tire',
            index_together={('path',)},
        ),
    ]
