# Generated by Django 2.1.7 on 2019-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpletire', '0006_auto_20190223_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='aspect_ratio',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='section_width',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='wheel_diameter',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
